[pytest]
testpaths =
    research/mic_ai_theory/model_identification/source/tests
    research/mic_ai_theory/snh_pwm/source/tests
pythonpath =
    research/mic_ai_theory/snh_pwm/source
    research/mic_ai_theory/model_identification/source
