from __future__ import annotations

"""
Export id_ref LUT JSON to a compact C header for Arduino/MCU use.
"""

import argparse
import json
from pathlib import Path
from typing import Dict, List


def _key(omega: float, load: float) -> str:
    return f"{omega:.6g}|{load:.6g}"


def _format_int_array(values: List[int], per_line: int = 8) -> str:
    lines: List[str] = []
    for idx in range(0, len(values), per_line):
        chunk = ", ".join(str(v) for v in values[idx : idx + per_line])
        lines.append(f"  {chunk},")
    return "\n".join(lines)


def _format_table(values: List[int], cols: int, per_line: int = 8) -> str:
    flat_lines: List[str] = []
    for row in range(0, len(values), cols):
        row_vals = values[row : row + cols]
        flat_lines.append(_format_int_array(row_vals, per_line=per_line))
    return "\n".join(flat_lines)


def main() -> None:
    parser = argparse.ArgumentParser(description="Export id_ref LUT JSON to C header.")
    parser.add_argument("--lut", required=True, help="Path to id_ref_lut.json")
    parser.add_argument("--out", required=True, help="Output header path (.h)")
    parser.add_argument("--symbol-prefix", default="unoq", help="Prefix for C symbols")
    parser.add_argument("--omega-scale", type=int, default=1024, help="Scale for omega_ref grid (q format)")
    parser.add_argument("--load-scale", type=int, default=1024, help="Scale for load_torque grid (q format)")
    parser.add_argument("--id-scale", type=int, default=1024, help="Scale for id_ref values (q format)")
    args = parser.parse_args()

    data = json.loads(Path(args.lut).read_text(encoding="utf-8"))
    omega_grid = [float(x) for x in data.get("omega_ref_grid", [])]
    load_grid = [float(x) for x in data.get("load_grid", [])]
    lut_map: Dict[str, float] = {str(k): float(v) for k, v in data.get("lut", {}).items()}

    if not omega_grid or not load_grid:
        raise ValueError("LUT must contain omega_ref_grid and load_grid.")

    omega_scale = int(args.omega_scale)
    load_scale = int(args.load_scale)
    id_scale = int(args.id_scale)

    omega_q = [int(round(v * omega_scale)) for v in omega_grid]
    load_q = [int(round(v * load_scale)) for v in load_grid]

    table: List[int] = []
    missing = []
    for omega in omega_grid:
        for load in load_grid:
            key = _key(omega, load)
            if key not in lut_map:
                missing.append(key)
                table.append(0)
            else:
                table.append(int(round(lut_map[key] * id_scale)))
    if missing:
        raise KeyError(f"Missing LUT entries: {missing[:8]}{'...' if len(missing) > 8 else ''}")

    prefix = "".join(ch if ch.isalnum() or ch == "_" else "_" for ch in str(args.symbol_prefix)).lower()
    guard = f"{prefix.upper()}_ID_REF_LUT_H"

    omega_len = len(omega_q)
    load_len = len(load_q)

    header = []
    header.append("// Auto-generated by mic_ai.tools.export_id_ref_lut_c")
    header.append(f"// Source: {Path(args.lut).as_posix()}")
    header.append("#ifndef " + guard)
    header.append("#define " + guard)
    header.append("")
    header.append("#include <stdint.h>")
    header.append("#include <stddef.h>")
    header.append("")
    header.append(f"#define {prefix.upper()}_OMEGA_SCALE {omega_scale}")
    header.append(f"#define {prefix.upper()}_LOAD_SCALE {load_scale}")
    header.append(f"#define {prefix.upper()}_ID_SCALE {id_scale}")
    header.append(f"#define {prefix.upper()}_OMEGA_SIZE {omega_len}")
    header.append(f"#define {prefix.upper()}_LOAD_SIZE {load_len}")
    header.append("")
    header.append(f"static const int32_t {prefix}_omega_grid_q[{omega_len}] = {{")
    header.append(_format_int_array(omega_q, per_line=8))
    header.append("};")
    header.append("")
    header.append(f"static const int32_t {prefix}_load_grid_q[{load_len}] = {{")
    header.append(_format_int_array(load_q, per_line=8))
    header.append("};")
    header.append("")
    header.append(f"static const int16_t {prefix}_id_ref_table_q[{omega_len * load_len}] = {{")
    header.append(_format_table(table, cols=load_len, per_line=8))
    header.append("};")
    header.append("")
    header.append("static inline size_t " + prefix + "_upper_index(const int32_t *grid, size_t n, int32_t value) {")
    header.append("  if (n == 0) { return 0; }")
    header.append("  if (value <= grid[0]) { return 0; }")
    header.append("  for (size_t i = 1; i < n; ++i) {")
    header.append("    if (value <= grid[i]) { return i; }")
    header.append("  }")
    header.append("  return n - 1;")
    header.append("}")
    header.append("")
    header.append("static inline int16_t " + prefix + "_id_ref_query_q(int32_t omega_q, int32_t load_q) {")
    header.append(f"  const size_t o_hi = {prefix}_upper_index({prefix}_omega_grid_q, {prefix.upper()}_OMEGA_SIZE, omega_q);")
    header.append(f"  const size_t l_hi = {prefix}_upper_index({prefix}_load_grid_q, {prefix.upper()}_LOAD_SIZE, load_q);")
    header.append("  const size_t o_lo = (o_hi == 0) ? 0 : (o_hi - 1);")
    header.append("  const size_t l_lo = (l_hi == 0) ? 0 : (l_hi - 1);")
    header.append("")
    header.append(f"  const int32_t o0 = {prefix}_omega_grid_q[o_lo];")
    header.append(f"  const int32_t o1 = {prefix}_omega_grid_q[o_hi];")
    header.append(f"  const int32_t l0 = {prefix}_load_grid_q[l_lo];")
    header.append(f"  const int32_t l1 = {prefix}_load_grid_q[l_hi];")
    header.append("")
    header.append(f"  const size_t idx00 = o_lo * {prefix.upper()}_LOAD_SIZE + l_lo;")
    header.append(f"  const size_t idx10 = o_hi * {prefix.upper()}_LOAD_SIZE + l_lo;")
    header.append(f"  const size_t idx01 = o_lo * {prefix.upper()}_LOAD_SIZE + l_hi;")
    header.append(f"  const size_t idx11 = o_hi * {prefix.upper()}_LOAD_SIZE + l_hi;")
    header.append("")
    header.append(f"  const int16_t v00 = {prefix}_id_ref_table_q[idx00];")
    header.append(f"  const int16_t v10 = {prefix}_id_ref_table_q[idx10];")
    header.append(f"  const int16_t v01 = {prefix}_id_ref_table_q[idx01];")
    header.append(f"  const int16_t v11 = {prefix}_id_ref_table_q[idx11];")
    header.append("")
    header.append("  if (o1 == o0 && l1 == l0) {")
    header.append("    return v00;")
    header.append("  }")
    header.append("")
    header.append("  const int32_t one = 1 << 15;")
    header.append("  int32_t t = 0;")
    header.append("  int32_t u = 0;")
    header.append("  if (o1 != o0) {")
    header.append("    t = (int32_t)(((int64_t)(omega_q - o0) << 15) / (int64_t)(o1 - o0));")
    header.append("  }")
    header.append("  if (l1 != l0) {")
    header.append("    u = (int32_t)(((int64_t)(load_q - l0) << 15) / (int64_t)(l1 - l0));")
    header.append("  }")
    header.append("")
    header.append("  const int64_t v0 = (((int64_t)(one - t) * v00) + ((int64_t)t * v10)) >> 15;")
    header.append("  const int64_t v1 = (((int64_t)(one - t) * v01) + ((int64_t)t * v11)) >> 15;")
    header.append("  const int64_t v = (((int64_t)(one - u) * v0) + ((int64_t)u * v1)) >> 15;")
    header.append("  return (int16_t)v;")
    header.append("}")
    header.append("")
    header.append("static inline int16_t " + prefix + "_id_ref_query(float omega, float load) {")
    header.append(f"  const int32_t omega_q = (int32_t)(omega * {prefix.upper()}_OMEGA_SCALE);")
    header.append(f"  const int32_t load_q = (int32_t)(load * {prefix.upper()}_LOAD_SCALE);")
    header.append("  return " + prefix + "_id_ref_query_q(omega_q, load_q);")
    header.append("}")
    header.append("")
    header.append("#endif")

    out_path = Path(args.out)
    out_path.parent.mkdir(parents=True, exist_ok=True)
    out_path.write_text("\n".join(header) + "\n", encoding="utf-8")


if __name__ == "__main__":
    main()
