[platformio]
default_envs = isolated_logic_only

[env:isolated_logic_only]
platform = ststm32@19.6.0
board = nucleo_g431rb
framework = stm32cube
upload_protocol = stlink
debug_tool = stlink
build_flags = -DMIC_ISOLATED_LOGIC_DIAGNOSTIC=1
