// Auto-generated by mic_ai.tools.export_id_ref_lut_c
// Source: outputs/id_ref_lut_motor1/id_ref_lut.json
#ifndef UNOQ_MOTOR1_ID_REF_LUT_H
#define UNOQ_MOTOR1_ID_REF_LUT_H

#include <stdint.h>
#include <stddef.h>

#define UNOQ_MOTOR1_OMEGA_SCALE 1024
#define UNOQ_MOTOR1_LOAD_SCALE 1024
#define UNOQ_MOTOR1_ID_SCALE 1024
#define UNOQ_MOTOR1_OMEGA_SIZE 5
#define UNOQ_MOTOR1_LOAD_SIZE 5

static const int32_t unoq_motor1_omega_grid_q[5] = {
  48255, 80425, 112595, 144765, 176934,
};

static const int32_t unoq_motor1_load_grid_q[5] = {
  205, 307, 410, 512, 614,
};

static const int16_t unoq_motor1_id_ref_table_q[25] = {
  369, 369, 369, 432, 546,
  369, 369, 369, 432, 546,
  369, 369, 369, 432, 546,
  369, 369, 369, 432, 546,
  369, 369, 369, 432, 546,
};

static inline size_t unoq_motor1_upper_index(const int32_t *grid, size_t n, int32_t value) {
  if (n == 0) { return 0; }
  if (value <= grid[0]) { return 0; }
  for (size_t i = 1; i < n; ++i) {
    if (value <= grid[i]) { return i; }
  }
  return n - 1;
}

static inline int16_t unoq_motor1_id_ref_query_q(int32_t omega_q, int32_t load_q) {
  const size_t o_hi = unoq_motor1_upper_index(unoq_motor1_omega_grid_q, UNOQ_MOTOR1_OMEGA_SIZE, omega_q);
  const size_t l_hi = unoq_motor1_upper_index(unoq_motor1_load_grid_q, UNOQ_MOTOR1_LOAD_SIZE, load_q);
  const size_t o_lo = (o_hi == 0) ? 0 : (o_hi - 1);
  const size_t l_lo = (l_hi == 0) ? 0 : (l_hi - 1);

  const int32_t o0 = unoq_motor1_omega_grid_q[o_lo];
  const int32_t o1 = unoq_motor1_omega_grid_q[o_hi];
  const int32_t l0 = unoq_motor1_load_grid_q[l_lo];
  const int32_t l1 = unoq_motor1_load_grid_q[l_hi];

  const size_t idx00 = o_lo * UNOQ_MOTOR1_LOAD_SIZE + l_lo;
  const size_t idx10 = o_hi * UNOQ_MOTOR1_LOAD_SIZE + l_lo;
  const size_t idx01 = o_lo * UNOQ_MOTOR1_LOAD_SIZE + l_hi;
  const size_t idx11 = o_hi * UNOQ_MOTOR1_LOAD_SIZE + l_hi;

  const int16_t v00 = unoq_motor1_id_ref_table_q[idx00];
  const int16_t v10 = unoq_motor1_id_ref_table_q[idx10];
  const int16_t v01 = unoq_motor1_id_ref_table_q[idx01];
  const int16_t v11 = unoq_motor1_id_ref_table_q[idx11];

  if (o1 == o0 && l1 == l0) {
    return v00;
  }

  const int32_t one = 1 << 15;
  int32_t t = 0;
  int32_t u = 0;
  if (o1 != o0) {
    t = (int32_t)(((int64_t)(omega_q - o0) << 15) / (int64_t)(o1 - o0));
  }
  if (l1 != l0) {
    u = (int32_t)(((int64_t)(load_q - l0) << 15) / (int64_t)(l1 - l0));
  }

  const int64_t v0 = (((int64_t)(one - t) * v00) + ((int64_t)t * v10)) >> 15;
  const int64_t v1 = (((int64_t)(one - t) * v01) + ((int64_t)t * v11)) >> 15;
  const int64_t v = (((int64_t)(one - u) * v0) + ((int64_t)u * v1)) >> 15;
  return (int16_t)v;
}

static inline int16_t unoq_motor1_id_ref_query(float omega, float load) {
  const int32_t omega_q = (int32_t)(omega * UNOQ_MOTOR1_OMEGA_SCALE);
  const int32_t load_q = (int32_t)(load * UNOQ_MOTOR1_LOAD_SCALE);
  return unoq_motor1_id_ref_query_q(omega_q, load_q);
}

#endif
