[env:bluepill_uart_pwm]
platform = ststm32
board = bluepill_f103c8
framework = stm32cube
upload_protocol = stlink
debug_tool = stlink
monitor_speed = 115200
build_src_filter = +<*> -<relay_test.cpp>

[env:bluepill_relay_test]
platform = ststm32
board = bluepill_f103c8
framework = stm32cube
upload_protocol = stlink
debug_tool = stlink
build_src_filter = +<relay_test.cpp>
